spring:
  application:
    name: coupon-consumer
server:
  port: 8081
management:
  metrics:
    tags:
      apllication:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus